import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Hunting Coder</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <nav className="bg-black flex items-center justify-between">
        <h1 className="text-white ml-12 font-bold text-2xl">Hunting Coder</h1>
        <ul className="flex pr-12 gap-20 items-center py-4 text-white font-semibold">
          <li className="hover:cursor-pointer">Home</li>
          <li className="hover:cursor-pointer">Blog</li>
          <li className="hover:cursor-pointer">Contact</li>
          <li className="hover:cursor-pointer">About</li>
        </ul>
      </nav>
      <main>
        <div className="flex items-center justify-around mt-10">
          <p className="text-2xl">
            A Blog for Hunting Coders by a Hunting Coder
          </p>
          <div>
            <p className="font-bold text-[16px]">by Mohammed Sajid</p>
          </div>
        </div>
      </main>
    </>
  );
}
